version: 0.1

phases:
    build:
        commands:
            - npm install -g yarn
            - yarn install
            - yarn webpack
artifacts:
    files:
        - index.html
        - favicon.ico
        - styles/*
        - images/*
        - dist/bundle.js